// GENERATED by scripts/generate-declarative-abilities.mjs -- do not hand-edit.
// Regenerate with: node scripts/generate-declarative-abilities.mjs
//
// Every ability abilityHooks.json flags damageRelevant that is covered ENTIRELY by
// declarative bitfields -- no onOffensiveMultiplier/onStat/etc. hook at all -- so
// there is nothing to hand-port; the flags themselves ARE the implementation.

import type { AbilityImpl } from '../types'

export const DECLARATIVE_ABILITIES: AbilityImpl[] = [
  { id: 'ABILITY_ADAPTABILITY', src: 'src/abilities.cc:1512', flags: { adaptability: true } },
  { id: 'ABILITY_CONJOURER_OF_DECEIT', src: 'src/abilities.cc:9336', flags: { breakable: true, magicGuard: true } },
  { id: 'ABILITY_CONTRARY', src: 'src/abilities.cc:1863', flags: { breakable: true } },
  { id: 'ABILITY_FORT_KNOX', src: 'src/abilities.cc:4383', flags: { fortKnox: true } },
  { id: 'ABILITY_FRIEND_GUARD', src: 'src/abilities.cc:1918', flags: { breakable: true } },
  { id: 'ABILITY_GUARD_DOG', src: 'src/abilities.cc:731', flags: { breakable: true } },
  { id: 'ABILITY_IMMOVABLE_OBJECT', src: 'src/abilities.cc:9619', flags: { magicGuard: true } },
  { id: 'ABILITY_IMPENETRABLE', src: 'src/abilities.cc:4188', flags: { magicGuard: true } },
  { id: 'ABILITY_MAGIC_BOUNCE', src: 'src/abilities.cc:2200', flags: { breakable: true } },
  { id: 'ABILITY_MAGIC_GUARD', src: 'src/abilities.cc:1579', flags: { magicGuard: true } },
  { id: 'ABILITY_MIRROR_ARMOR', src: 'src/abilities.cc:3229', flags: { breakable: true } },
  { id: 'ABILITY_RELIC_STONE', src: 'src/abilities.cc:10451', flags: { breakable: true } },
  { id: 'ABILITY_ROCK_HEAD', src: 'src/abilities.cc:1298', flags: { breakable: true, noRecoil: true } },
  { id: 'ABILITY_SHIELD_DUST', src: 'src/abilities.cc:708', flags: { breakable: true } },
  { id: 'ABILITY_SKILL_LINK', src: 'src/abilities.cc:1517', flags: { skillLink: true } },
  { id: 'ABILITY_STEEL_BARREL', src: 'src/abilities.cc:4973', flags: { noRecoil: true } },
  { id: 'ABILITY_STICKY_HOLD', src: 'src/abilities.cc:1245', flags: { breakable: true } },
  { id: 'ABILITY_STURDY', src: 'src/abilities.cc:533', flags: { breakable: true } },
  { id: 'ABILITY_SUCTION_CUPS', src: 'src/abilities.cc:725', flags: { breakable: true } },
  { id: 'ABILITY_SURVIVOR_BIAS', src: 'src/abilities.cc:12286', flags: { breakable: true } },
  { id: 'ABILITY_UNAWARE', src: 'src/abilities.cc:1692', flags: { unaware: true, breakable: true } },
  { id: 'ABILITY_WONDER_SKIN', src: 'src/abilities.cc:2105', flags: { fortKnox: true } },
]
