// GENERATED by scripts/generate-declarative-abilities.mjs -- hand-edit freely by
// DELETING an entry once you port it to a real batch file (01-*.ts, 02-*.ts, ...);
// do not regenerate this file wholesale once porting has started, or it will
// re-add abilities that were already ported. Regenerate only right after an
// abilityHooks.json update, then re-remove the ones already ported elsewhere.
//
// Every damage-relevant ability with a real lambda/alias/macro hook -- i.e.
// everything Task 10 still needs to port -- starts here as an explicit
// UNMODELLED stub, so the coverage gate (abilities/coverage.test.ts) passes from
// day one instead of only once every single ability is done. This file shrinking
// to zero entries IS the ability-porting progress bar.

import type { AbilityEntry } from '../types'

export const UNMODELLED_ABILITIES: AbilityEntry[] = [
  { id: 'ABILITY_APE_SHIFT', src: 'src/abilities.cc:9036', unmodelled: 'not yet ported (hooks: onCrit)' },
  { id: 'ABILITY_AVENGER', src: 'src/abilities.cc:3851', unmodelled: 'not yet ported (hooks: onOffensiveMultiplier)' },
  { id: 'ABILITY_BLOOD_STIGMA', src: 'src/abilities.cc:8373', unmodelled: 'not yet ported (hooks: onOffensiveMultiplier)' },
  { id: 'ABILITY_BONE_ZONE', src: 'src/abilities.cc:4508', unmodelled: 'not yet ported (hooks: onAfterTypeEffectiveness)' },
  { id: 'ABILITY_COLOR_SPECTRUM', src: 'src/abilities.cc:8710', unmodelled: 'not yet ported (hooks: onOffensiveMultiplier)' },
  { id: 'ABILITY_COSMIC_DAZE', src: 'src/abilities.cc:6730', unmodelled: 'not yet ported (hooks: onOffensiveMultiplier)' },
  { id: 'ABILITY_CRYSTALLIZE', src: 'src/abilities.cc:3729', unmodelled: 'not yet ported (hooks: onMoveType, onOffensiveMultiplier)' },
  { id: 'ABILITY_DEADLY_PRECISION', src: 'src/abilities.cc:11162', unmodelled: 'not yet ported (hooks: onMoldBreaker)' },
  { id: 'ABILITY_DREAMCATCHER', src: 'src/abilities.cc:3983', unmodelled: 'not yet ported (hooks: onOffensiveMultiplier)' },
  { id: 'ABILITY_DREAMSCAPE', src: 'src/abilities.cc:10367', unmodelled: 'not yet ported (hooks: onOffensiveMultiplier)' },
  { id: 'ABILITY_ETERNAL_FLOWER', src: 'src/abilities.cc:11630', unmodelled: 'not yet ported (hooks: onStat)' },
  { id: 'ABILITY_ILLUSION', src: 'src/abilities.cc:2118', unmodelled: 'not yet ported (hooks: onOffensiveMultiplier)' },
  { id: 'ABILITY_LETHARGY', src: 'src/abilities.cc:4934', unmodelled: 'not yet ported (hooks: onOffensiveMultiplier)' },
  { id: 'ABILITY_MADNESS_ENHANCEMENT', src: 'src/abilities.cc:9921', unmodelled: 'not yet ported (hooks: onDefensiveMultiplier)' },
  { id: 'ABILITY_NORMALIZE', src: 'src/abilities.cc:1558', unmodelled: 'not yet ported (hooks: onMoveType, onOffensiveMultiplier, onTypeEffectiveness)' },
  { id: 'ABILITY_PRETTY_PRINCESS', src: 'src/abilities.cc:5258', unmodelled: 'not yet ported (hooks: onOffensiveMultiplier)' },
  { id: 'ABILITY_SHEER_FORCE', src: 'src/abilities.cc:1855', unmodelled: 'not yet ported (hooks: onOffensiveMultiplier)' },
  { id: 'ABILITY_SOOTHSAYER', src: 'src/abilities.cc:9409', unmodelled: 'not yet ported (hooks: breakable, onAfterTypeEffectiveness)' },
  { id: 'ABILITY_SUPERCONDUCTOR', src: 'src/abilities.cc:8187', unmodelled: 'not yet ported (hooks: onMoveType, onOffensiveMultiplier)' },
  { id: 'ABILITY_TANGLED_FEET', src: 'src/abilities.cc:1383', unmodelled: 'not yet ported (hooks: onChooseDefensiveStat)' },
  { id: 'ABILITY_VICTORY_BOMB', src: 'src/abilities.cc:8980', unmodelled: 'not yet ported (hooks: onMoveType)' },
]
